version: "3.8"

services:
  redis:
    image: redis
    container_name: "redis3205"
    restart: unless-stopped
    env_file: ".env"
    command: redis-server --requirepass redis_secret
    ports:
      - "6379:6379"